defaults:
  - base

job_name: "MHC_protein_8CMC"

output_path: "outputs/MHC/MHC_protein_8CMC"
checkpoint_path: "RFAA_paper_weights.pt"
database_params:
  sequencedb: ""
  hhdb: "pdb100_2021Mar03/pdb100_2021Mar03"
  command: make_msa.sh
  num_cpus: 6
  mem: 64

protein_inputs:
  B:
    fasta_file: "inputs/MHC/8CMC/rcsb_pdb_8CMC_B.fasta"
  A:
    fasta_file: "inputs/MHC/8CMC/rcsb_pdb_8CMC_A.fasta"
  C:
    fasta_file: "inputs/MHC/8CMC/rcsb_pdb_8CMC_C.fasta"
