defaults:
  - base

job_name: "MHC_protein_4U6Y"

output_path: "outputs/MHC/MHC_protein_4U6Y"
checkpoint_path: "RFAA_paper_weights.pt"
database_params:
  sequencedb: ""
  hhdb: "pdb100_2021Mar03/pdb100_2021Mar03"
  command: make_msa.sh
  num_cpus: 6
  mem: 64

protein_inputs:
  A:
    fasta_file: "inputs/MHC/4U6Y/rcsb_pdb_4U6Y_A.fasta"
  C:
    fasta_file: "inputs/MHC/4U6Y/rcsb_pdb_4U6Y_C.fasta"
  B:
    fasta_file: "inputs/MHC/4U6Y/rcsb_pdb_4U6Y_B.fasta"
