defaults:
  - base

job_name: "MHC_protein_8ROO"

output_path: "outputs/MHC/MHC_protein_8ROO"
checkpoint_path: "RFAA_paper_weights.pt"
database_params:
  sequencedb: ""
  hhdb: "pdb100_2021Mar03/pdb100_2021Mar03"
  command: make_msa.sh
  num_cpus: 6
  mem: 64

protein_inputs:
  C:
    fasta_file: "inputs/MHC/8ROO/rcsb_pdb_8ROO_C.fasta"
  B:
    fasta_file: "inputs/MHC/8ROO/rcsb_pdb_8ROO_B.fasta"
  A:
    fasta_file: "inputs/MHC/8ROO/rcsb_pdb_8ROO_A.fasta"
