defaults:
  - base

job_name: "MHC_protein_5COE"

output_path: "outputs/MHC/MHC_protein_5COE"
checkpoint_path: "RFAA_paper_weights.pt"
database_params:
  sequencedb: ""
  hhdb: "pdb100_2021Mar03/pdb100_2021Mar03"
  command: make_msa.sh
  num_cpus: 6
  mem: 64

protein_inputs:
  A:
    fasta_file: "inputs/MHC/5COE/rcsb_pdb_5COE_A.fasta"
