defaults:
  - base

job_name: "MHC_protein_5N1Y"

output_path: "outputs/MHC/MHC_protein_5N1Y"
checkpoint_path: "RFAA_paper_weights.pt"
database_params:
  sequencedb: ""
  hhdb: "pdb100_2021Mar03/pdb100_2021Mar03"
  command: make_msa.sh
  num_cpus: 6
  mem: 64

protein_inputs:
  B:
    fasta_file: "inputs/MHC/5N1Y/rcsb_pdb_5N1Y_B.fasta"
  C:
    fasta_file: "inputs/MHC/5N1Y/rcsb_pdb_5N1Y_C.fasta"
  A:
    fasta_file: "inputs/MHC/5N1Y/rcsb_pdb_5N1Y_A.fasta"
