defaults:
  - base

job_name: "TCR_protein_8RYN"

output_path: "outputs/TCR/TCR_protein_8RYN"
checkpoint_path: "RFAA_paper_weights.pt"
database_params:
  sequencedb: ""
  hhdb: "pdb100_2021Mar03/pdb100_2021Mar03"
  command: make_msa.sh
  num_cpus: 6
  mem: 64

protein_inputs:
  C:
    fasta_file: "inputs/TCR/8RYN/rcsb_pdb_8RYN_C.fasta"
  B:
    fasta_file: "inputs/TCR/8RYN/rcsb_pdb_8RYN_B.fasta"
  D:
    fasta_file: "inputs/TCR/8RYN/rcsb_pdb_8RYN_D.fasta"
  A:
    fasta_file: "inputs/TCR/8RYN/rcsb_pdb_8RYN_A.fasta"
  E:
    fasta_file: "inputs/TCR/8RYN/rcsb_pdb_8RYN_E.fasta"
