defaults:
  - base

job_name: "TCR_protein_2BNU"

output_path: "outputs/TCR/TCR_protein_2BNU"
checkpoint_path: "RFAA_paper_weights.pt"
database_params:
  sequencedb: ""
  hhdb: "pdb100_2021Mar03/pdb100_2021Mar03"
  command: make_msa.sh
  num_cpus: 6
  mem: 64

protein_inputs:
  B:
    fasta_file: "inputs/TCR/2BNU/rcsb_pdb_2BNU_B.fasta"
  A:
    fasta_file: "inputs/TCR/2BNU/rcsb_pdb_2BNU_A.fasta"
