defaults:
  - base

job_name: "TCR_protein"

output_path: "outputs/TCR"
checkpoint_path: RFAA_paper_weights.pt
database_params:
  sequencedb: ""
  hhdb: "pdb100_2021Mar03/pdb100_2021Mar03"
  command: make_msa.sh
  num_cpus: 8
  mem: 64
  
protein_inputs: 
  A:
    fasta_file: examples/protein/rcsb_pdb_8GOP_A.fasta
  B:
    fasta_file: examples/protein/rcsb_pdb_8GOP_B.fasta
na_inputs: null
sm_inputs: null
covale_inputs:  null
residue_replacement: null
