defaults:
  - base

job_name: "TCR_protein_6CPH"

output_path: "outputs/TCR/TCR_protein_6CPH"
checkpoint_path: "RFAA_paper_weights.pt"
database_params:
  sequencedb: ""
  hhdb: "pdb100_2021Mar03/pdb100_2021Mar03"
  command: make_msa.sh
  num_cpus: 6
  mem: 64

protein_inputs:
  A:
    fasta_file: "inputs/TCR/6CPH/rcsb_pdb_6CPH_A.fasta"
  B:
    fasta_file: "inputs/TCR/6CPH/rcsb_pdb_6CPH_B.fasta"
