defaults:
  - base

job_name: "TCR_protein_5D7K"

output_path: "outputs/TCR/TCR_protein_5D7K"
checkpoint_path: "RFAA_paper_weights.pt"
database_params:
  sequencedb: ""
  hhdb: "pdb100_2021Mar03/pdb100_2021Mar03"
  command: make_msa.sh
  num_cpus: 6
  mem: 64

protein_inputs:
  A:
    fasta_file: "inputs/TCR/5D7K/rcsb_pdb_5D7K_A.fasta"
  B:
    fasta_file: "inputs/TCR/5D7K/rcsb_pdb_5D7K_B.fasta"
