defaults:
  - base

job_name: "TCR_protein_7ZT7"

output_path: "outputs/TCR/TCR_protein_7ZT7"
checkpoint_path: "RFAA_paper_weights.pt"
database_params:
  sequencedb: ""
  hhdb: "pdb100_2021Mar03/pdb100_2021Mar03"
  command: make_msa.sh
  num_cpus: 6
  mem: 64

protein_inputs:
  C:
    fasta_file: "inputs/TCR/7ZT7/rcsb_pdb_7ZT7_C.fasta"
  D:
    fasta_file: "inputs/TCR/7ZT7/rcsb_pdb_7ZT7_D.fasta"
  A:
    fasta_file: "inputs/TCR/7ZT7/rcsb_pdb_7ZT7_A.fasta"
  B:
    fasta_file: "inputs/TCR/7ZT7/rcsb_pdb_7ZT7_B.fasta"
